### PR TITLE
Fix/unbinding

### LINKED ISSUE #176: The agents aren't unbinding as frequently as they should
## Description

if they are already bound, the don't unbind 

[the fix is in my draft PR](https://github.com/simularium/binding-sim-edu/pull/175/files#diff-095f6eed2b1526d36c8d747fcab8fbbd1ce0c91446776bc4ae640eac943e9cfd)

### PR DESCRIPTION
**Pull request by meganrm**
Problem
=======
Estimated review size: small

closes #176 
When the app updates all the instances, it was only checking unbinding events on agents that overlapped, not ones that were perfectly bound. 

Solution
========
call check if unbind function within step 

## Type of change
Please delete options that are not relevant.

* Bug fix (non-breaking change which fixes an issue)

Steps to Verify:
----------------
1. bun dev
2. if you run through the activity you still get a kd of around 0.75

### CODE REVIEW

File: src/simulation/LiveSimulationData.ts [hunk 1]
```diff
@@ -32,8 +32,8 @@ const agentB: InputAgent = {
     initialConcentration: 0,
     radius: 1,
     partners: [0],
-    kOn: 0.6,
-    kOff: 0.5,
+    kOn: 0.9,
+    kOff: 0.01,
```
Comment (meganrm) [inline src/simulation/LiveSimulationData.ts:36]: these had to be changed because the new unbinding means to have the same binding affinity the k off rate had to be a lot lower

File: src/simulation/LiveSimulationData.ts [hunk 2]
```diff
@@ -49,7 +49,7 @@ const agentC: InputAgent = {
 };
 
 const kds = {
-    [Module.A_B_AB]: 1,
+    [Module.A_B_AB]: 0.75,
```
Comment (meganrm) [inline src/simulation/LiveSimulationData.ts:52]: this is a more accurate number for what gets calculated

**Review by interim17 — APPROVED** [review]

**Review by toloudis — APPROVED** [review]

File: src/simulation/BindingSimulator2D.ts [hunk 3]
```diff
@@ -427,7 +427,14 @@ export default class BindingSimulator implements IClientSimulatorImpl {
...
 
         for (let i = 0; i < this.instances.length; ++i) {
-            this.instances[i].oneStep(this.size, this.timeFactor);
+            const unbindingOccurred = this.instances[i].oneStep(
+                this.size,
+                this.timeFactor
+            );
+            if (unbindingOccurred) {
+                this.currentNumberOfUnbindingEvents++;
+                this.currentNumberBound--;
```
[the remark this answers is not in the document]
Comment (meganrm) [reply src/simulation/BindingSimulator2D.ts:436]: Not that I can think of. The currentNumberBound is used to graph the product and it’s pretty smooth and consistent. Agents never go away, there’s periodic boundary behind the edges of the viewport
